name: test-powershell-action
description: 'test description'
branding:
  icon: check-circle
  color: blue
inputs:
  number1:
    description: 'the first number'
    required: true
  number2:
    description: 'the second number'
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/SampleScript.ps1
      shell: pwsh
