name: test-powershell-action
description: 'test description'
branding:
  icon: check-circle
  color: blue
inputs:
  baseurl:
    description: 'baseURL of ASOC API'
    required: true
  asoc_key:
    description: 'API key for connecting to ASoC.'
    required: true
  asoc_secret:
    description: 'Secret for connecting to ASoC.'
    required: true
  application_name:
    description: 'The ASoC application id where your scan will appear.'
    required: true
  scan_name:
    description: 'The name of the scan created in ASoC.'
    required: false
  scan_type:
    description: 'The type of scan - staging or production'
    required: false
  starting_URL:
    description: 'The starting URL of the DAST scan'
    required: false
  login_method:
    description: 'Login Method of the scan, can be none, userpass, or record'
    required: false
runs:
  using: "composite"
  steps:
    - run: |
        # $env:INPUT_TEST = "${{ inputs.TEST }}"
        $env:INPUT_baseurl = "${{ inputs.baseurl }}"
        $env:INPUT_asoc_key = "${{inputs.asoc_key}}"
        $env:INPUT_asoc_secret = "${{inputs.asoc_secret}}"
        $env:INPUT_application_name = "${{inputs.application_name}}"
        $env:INPUT_scan_name = "${{ inputs.scan_name }}"
        $env:INPUT_scan_type = "${{ inputs.scan_type }}"
        $env:INPUT_starting_URL = "${{ inputs.starting_URL }}"
        $env:INPUT_login_method = "${{ inputs.login_method }}"

        ${{ github.action_path }}/asoc.ps1
      shell: pwsh
