name: test-powershell-action
description: 'test description'
branding:
  icon: check-circle
  color: blue
inputs:
  baseurl:
    description: 'baseURL of ASOC API'
    required: true
  asoc_key:
    description: 'API key for connecting to ASoC.'
    required: true
  asoc_secret:
    description: 'Secret for connecting to ASoC.'
    required: true
  application_id:
    description: 'The ASoC application id where your scan will appear.'
    required: true
  scan_name:
    description: 'The name of the scan created in ASoC.'
    required: false

runs:
  using: "composite"
  steps:
    - run: 
        ${{ github.action_path }}/asoc.ps1
        $env:INPUT_BASEURL = ${{ inputs.baseurl }}
      shell: pwsh
